dnsItems = [
                {'A': "ignition."},
                {'A': "registry."},
                {'A': "api."},
                {'A': "api-int."},
                {'A': "console-openshift-console.apps."},
                {'A': "myapp.apps."},
                {'A': "etcd-0."},
                {'A': "etcd-1."},
                {'A': "etcd-2."},
                {'A': "bootstrap."},
                {'A': "master-0."},
                {'A': "master-1."},
                {'A': "master-2."},
                {'A': "worker-0."},
                {'A': "worker-1."},
                {'A': "worker-2."},
                {'SRV': "_etcd-server-ssl._tcp."},
              ]